name: Waiting For Review Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  apply_needs_review_label:
    runs-on: ubuntu-latest
    name: Apply Label
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Build apply_needs_review_label
        run: ACTION_NAME=apply_needs_review_label EXTENSION=ts yarn build_action
      - name: Run apply_needs_review_label
        uses: ./.github/custom_actions/apply_needs_review_label
        with:
          hours-before-add-label: 0
          label-name: 'needs-review'
