name: Waiting For Review Labeler

on:
  schedule:
  # Crontab Every Hour
  - cron: '0 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: EricStrohl/review-time-alert@main
        with:
          hours-before-add-label: 1
          label-name: 'needs-review'
