name: Waiting For Review Labeler

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/review-time-alert@main
        with:
          hours-before-label-add: 2
          label-name: 'waiting for review'

