name: Waiting For Review Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: EricStrohl/waiting-for-review-labeler@main
        with:
          hours-before-add-label: 0
          label-name: 'needs-review'
