name: Waiting For Review Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  apply_needs_review_label:
    runs-on: ubuntu-latest
    name: Apply Label
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Build apply_needs_review_label
        run: ACTION_NAME=apply_needs_review_label EXTENSION=ts yarn build_action
      - name: Run apply_needs_review_label
        uses: ./.github/custom_actions/apply_needs_review_label
        with:
          hours-before-add-label: 0
          label-name: 'needs-review'
      - name: Notify on Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "Pull Request ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Pull Request opened by ${{ github.actor }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Branch ${{ github.head_ref }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
